version: '3.8'

services:
  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ../data:/docker-entrypoint-initdb.d
    networks:
      - postgresql
networks:
  postgresql:
    driver: bridge