services:
    mongodb:
      image: mongodb/mongodb-community-server:6.0-ubi8
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      ports:
        - '27017:27017'
      volumes:
        - db-data:/data/db
volumes:
    db-data:
