version: '3.6'

services:
  # Database
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "RANDOM-SECURE-PASSWORD-MUST-BE-DEFINED-HERE!"
      MYSQL_DATABASE: example
      MYSQL_USER: nonroot
      MYSQL_PASSWORD: "RANDOM-SECURE-PASSWORD-MUST-BE-DEFINED-HERE!"
      TZ: America/El_Salvador
    networks:
      - mysql_net
  # adminer (OPTIONAL)
  # This is just a lightweight client to connect to your MySql instance
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql_net
      
networks:
  mysql_net:
volumes:
  db_data:
